[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Perspective Viewport"
description="The simplest python extension example. Use it as a starting point for your extensions."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Example"

# Keywords for the extension
keywords = ["kit", "example"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}
"omni.kit.viewport.window" = {}
"omni.kit.widget.viewport" = {}
"omni.timeline" = {}
"omni.kit.viewport.registry" = {}
"omni.kit.manipulator.camera" = {}
"omni.kit.manipulator.prim" = {}
"omni.kit.manipulator.selection" = {}
# "omni.kit.viewport.window.dragdrop" = {}


# Main python module this extension provides, it will be publicly available as "import omni.hello.world".
[[python.module]]
name = "my.perspective.viewport"

[settings]
# Default to "Viewport Next" in case legacy viewport is also loaded
# clients should be able to override this when they know that its not.
exts."my.perspective.viewport".startup.windowName="Sketch In Context"
# Setting to disable opening a Window instance when loaded
exts."my.perspective.viewport".startup.disableWindowOnLoad=false

